spring:
  application:
    name: health-ask
#服务端口
server:
  port: 8080

# 自定义属性，可以在Controller中读取
application:
  hello: Hello Angel From application

#日志输出配置
logging:
  path: ${app.log.path:${user.home}/health_ask/logs}
#  pattern:
#    console: "[%d] %-5level %msg%n"
  level:
    com.hebeu.ask.spider.processor: debug
    com.hebeu.ask.seo.search: debug
    com.hebeu.ask.web.controller: debug
    com.hebeu.ask.service.view: debug
    com.hebeu.ask.web.shiro: debug


# 定时任务开关
task:
  switch: true

#数据库相关配置
#spring:
#  datasource:
#    url: jjdbc:mysql://47.94.251.186:3306/health_ask?useUnicode=true&amp;characterEncoding=UTF-8
#    username: root
#    password: uAiqwVwjJ8-i
#    driver-class-name: com.mysql.jdbc.Driver

# REDIS (RedisProperties)
#redis配置
  redis:
#  数据库索引
    database: 0
#    服务器地址
    host: 47.94.251.186
#    服务器连接端口
    port: 6379
#    链接密码
    password: cdh19950820
#    链接池
    pool:
#    最大连接数（负值表示没有限制）
      max-active: 8
#      最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
#      最大空闲链接
      max-idle: 8
#      最小空闲链接
      min-idle: 0
#    链接超时时间（毫秒）
    timeout: 0
